version: '3.7'

services:
  db:
    image: mysql:8.0.23
    container_name: mysql_01
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: swinggy
      TZ: 'Asia/Tokyo'
    command: --default_authentication_plugin=mysql_native_password

  app:
    build: ./
    container_name: app_01
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db
    env_file:
      - .env
    command: java -jar demo-0.0.1.jar
