version: '3.7'

services:
  db:
    image: mysql:8.0.23
    container_name: mysql_01
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: golf_app_db
      BIND_ADDRESS: 0.0.0.0
    command: --default_authentication_plugin=mysql_native_password

  app:
    build: ./
    container_name: app_01
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db
    entrypoint:
      - dockerize
      - -timeout
      - 30s
      - -wait
      - tcp://db:3306
    command: java -jar demo-0.0.1.jar
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
