FROM gradle:6.8.3-jdk11 AS BUILDER

COPY . /
RUN gradle build --debug


FROM openjdk:11-jre AS RUNNER

COPY /build/libs/demo-0.0.1-SNAPSHOT.jar ./app/
WORKDIR ./app

ENV  LOG_LEVEL=${LOG_LEVEL}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
ENV AWS_REGION=${AWS_REGION}
ENV AWS_S3_PROFILE_IMAGE_DIRECTORY=${AWS_S3_PROFILE_IMAGE_DIRECTORY}
ENV AWS_S3_DEFAULT_PROFILE_IMAGE_URL=${AWS_S3_DEFAULT_PROFILE_IMAGE_URL}
ENV DATASOURCE=${DATASOURCE}

ENTRYPOINT ["java","-jar","demo-0.0.1-SNAPSHOT.jar"]