version: '3.7'

services:
  db:
    image: mysql:8.0
    container_name: mysql_01
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: golf_app_db
      BIND_ADDRESS: 0.0.0.0
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_general_ci","--default_authentication_plugin=mysql_native_password"]

  app:
    build: ./
    container_name: app_01
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db